"""create_job_table_final

Revision ID: 22d541199172
Revises: 87fda0c99183
Create Date: 2026-05-02 03:10:54.150492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d541199172'
down_revision: Union[str, Sequence[str], None] = '87fda0c99183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('skills_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skills_id'], ['Skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['Workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Job_customer_id'), 'Job', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Job_customer_id'), table_name='Job')
    op.drop_table('Job')
    # ### end Alembic commands ###
