"""add_rating_cache

Revision ID: 355efa2ed6e0
Revises: 6ffb18c39435
Create Date: 2026-05-05 02:49:04.442381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355efa2ed6e0'
down_revision: Union[str, Sequence[str], None] = '6ffb18c39435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['Workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'job_id', name='_customer_job_rating_uc')
    )
    op.create_index(op.f('ix_Rating_customer_id'), 'Rating', ['customer_id'], unique=False)
    op.add_column('Workers', sa.Column('average_rating', sa.FLOAT(), nullable=True))
    op.add_column('Workers', sa.Column('total_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workers', 'total_rating')
    op.drop_column('Workers', 'average_rating')
    op.drop_index(op.f('ix_Rating_customer_id'), table_name='Rating')
    op.drop_table('Rating')
    # ### end Alembic commands ###
