"""add last_available_at to workers

Revision ID: 75270570f915
Revises: 302bbd8648b3
Create Date: 2026-04-29 05:49:41.687677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75270570f915'
down_revision: Union[str, Sequence[str], None] = '302bbd8648b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workers', sa.Column('last_available_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workers', 'last_available_at')
    # ### end Alembic commands ###
