"""added_partial_index_for_active_jobs

Revision ID: 7c3554a72d24
Revises: 355efa2ed6e0
Create Date: 2026-05-08 04:01:57.230649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3554a72d24'
down_revision: Union[str, Sequence[str], None] = '355efa2ed6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_one_active_job_per_worker', 'Job', ['worker_id'], unique=True, postgresql_where=sa.text("status IN ('accepted', 'in_progress')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_one_active_job_per_worker', table_name='Job', postgresql_where=sa.text("status IN ('accepted', 'in_progress')"))
    # ### end Alembic commands ###
