"""Add skills trigram index

Revision ID: 894199af7268
Revises: e11d4697ff52
Create Date: 2026-05-17 02:39:38.287387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894199af7268'
down_revision: Union[str, Sequence[str], None] = 'e11d4697ff52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index('ix_skills_name_trgm', 'Skills', ['skills_name'], unique=False, postgresql_using='gin', postgresql_ops={'skills_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_name_trgm', table_name='Skills', postgresql_using='gin', postgresql_ops={'skills_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
