"""add hourly_rate to worker profile

Revision ID: 8cb6889018f2
Revises: 938a977e494d
Create Date: 2026-05-15 05:28:18.443724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb6889018f2'
down_revision: Union[str, Sequence[str], None] = '938a977e494d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workers', sa.Column('hourly_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workers', 'hourly_rate')
    # ### end Alembic commands ###
