"""add_active_and_soft_delete

Revision ID: 938a977e494d
Revises: 7c3554a72d24
Create Date: 2026-05-12 02:53:29.106468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938a977e494d'
down_revision: Union[str, Sequence[str], None] = '7c3554a72d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute('UPDATE "Job" SET is_deleted = False')
    op.execute('UPDATE "Users" SET is_active = True')

    
    op.alter_column('Job', 'is_deleted', nullable=False)
    op.alter_column('Users', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_active')
    op.drop_column('Job', 'is_deleted')
    # ### end Alembic commands ###
