"""Adding Agreed_price column

Revision ID: e11d4697ff52
Revises: 8cb6889018f2
Create Date: 2026-05-15 06:28:28.411626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11d4697ff52'
down_revision: Union[str, Sequence[str], None] = '8cb6889018f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('agreed_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Job', 'agreed_price')
    # ### end Alembic commands ###
